# Generated by Django 4.2.28 on 2026-02-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/")),
                ("results_json", models.JSONField(blank=True, null=True)),
                ("n_components", models.IntegerField(default=50)),
                ("psnr", models.FloatField(blank=True, null=True)),
                ("ssim", models.FloatField(blank=True, null=True)),
                ("k_90", models.IntegerField(blank=True, null=True)),
                ("k_95", models.IntegerField(blank=True, null=True)),
                ("k_99", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("max_components", models.IntegerField(blank=True, null=True)),
                ("compute_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Image analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
