# Generated by Django 4.2.28 on 2026-02-06 14:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='The Knowledge Graph in valid JSON-LD format')),
            ],
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField(help_text='The user instruction for this transformation')),
                ('model_used', models.CharField(help_text='The LLM model used (e.g., gemma3)', max_length=255)),
                ('input_kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations_as_input', to='core.knowledgegraph')),
                ('output_kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations_as_output', to='core.knowledgegraph')),
            ],
        ),
        migrations.CreateModel(
            name='AtomicOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(help_text='Type of operation (from diff.OpType)', max_length=50)),
                ('target_id', models.CharField(help_text='ID of the node or edge being modified', max_length=1024)),
                ('payload', models.JSONField(blank=True, help_text='Additional data for the operation (new values, etc.)', null=True)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.transformation')),
            ],
        ),
    ]
